# Pickles Update Configuration File
# This is the default configuration.
# User can override by creating $HOME/.config/pickles-linux/pickles-update/pudate.conf

# Keep logs
keep_log=true

# How long to keep logs in days
keep_log_length=14

# Log file save location
log_file_save_location="$HOME/.config/pickles-linux/logs/"

# AUR build directory
aur_build_dir="$HOME/.cache/pickles_aur_build"

# Keep AUR build cache after update
keep_aur_build_cache=false

# Default to rate mirrors on update
rate_mirrors_default=false